name: CI/CD

on: 
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: chechout code
        uses: actions/checkout@v4
      
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: run test
        run: |
          PYTHONPATH=. pytest
          pytest

      - name: log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: build docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/math-api:latest
          docker build -t $IMAGE_NAME .
      - name: push docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/math-api:latest
          docker push $IMAGE_NAME